dataloader:
  dataset:
    _target_: geoarches.dataloaders.era5pred.Era5ForecastWithPrediction
    path: data/era5_240/full/
    lead_time_hours: 24
    load_prev: true
    load_hard_neg: false
    domain: train
  validation_args:
    multistep: 2
    domain: val
  test_args:
    multistep: 2
    domain: test_z0012
stats:
  module:
    _target_: geoarches.utils.normalization.NormalizationStatistics
    norm_file: pangu_norm_stats.nc
    residual_stats_path: deltapred24_aws_denorm.nc
    variables:
      surface:
          - 10m_u_component_of_wind
          - 10m_v_component_of_wind
          - 2m_temperature
          - mean_sea_level_pressure
      level:
          - geopotential
          - u_component_of_wind
          - v_component_of_wind
          - temperature
          - specific_humidity
          - vertical_velocity
    levels: [50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]
  compute_loss_coeffs_args:
    latitude: 121
    use_weatherbench_lat_coeffs: true
    loss_weight_per_variable:
      surface: [0.1, 0.1, 1.0, 0.1]
      level: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  compute_state_scaler_args:
    state_normalization: pred
    downweight_vertical_velocity: true
module:
  project: atmo-diffusion
  module:
    _target_: geoarches.lightning_modules.diffusion.DiffusionModule
    name: archesweathergen-s-ft
    cond_dim: 256
    scheduler: flow
    prediction_type: sample
    beta_schedule: squaredcos_cap_v2
    snr_gamma: 0
    uncond_proba: 0.0
    load_deterministic_model:
    - modelstore/archesweather-m-seed0
    - modelstore/archesweather-m-seed1
    - modelstore/archesweather-m-skip-seed0
    - modelstore/archesweather-m-skip-seed1
    learn_residual: pred
    conditional: prev+det
    loss_weighting_strategy: debiased
    pow: 2
    use_classifier: false
    add_input_state: false
    snr_strategy: None
    lr: 0.0001
    betas:
    - 0.95
    - 0.99
    weight_decay: 0.01
    num_warmup_steps: 500
    num_training_steps: 60000
    cond_times_backward_compatible: true
  val:
    num_members: 5
    rollout_iterations: 1
    metrics:
    - _target_: geoarches.metrics.ensemble_metrics.Era5EnsembleMetrics
    - _target_: geoarches.metrics.brier_skill_score.Era5BrierSkillScore
    metrics_kwargs:
      rollout_iterations: 1
      lead_time_hours: 24
      save_memory: false
  inference:
    num_steps: 25
    num_members: 10
    rollout_iterations: 10
    cf_guidance: 1
    s_churn: 0.0
    scale_input_noise: 1.05
    save_test_outputs: false
    metrics:
      era5_ensemble:
        _target_: geoarches.metrics.ensemble_metrics.Era5EnsembleMetrics
      era5_brier:
        _target_: geoarches.metrics.brier_skill_score.Era5BrierSkillScore
    metrics_kwargs:
      rollout_iterations: 10
      lead_time_hours: 24
      save_memory: false
  backbone:
    _target_: geoarches.backbones.archesweather.ArchesWeatherCondBackbone
    tensor_size:
    - 8
    - 60
    - 120
    emb_dim: 192
    cond_dim: 256
    window_size:
    - 1
    - 6
    - 10
    droppath_coeff: 0.2
    dropout: 0
    depth_multiplier: 1
    use_skip: true
    first_interaction_layer: linear
    axis_attn: true
    mlp_layer: swiglu
    mlp_ratio: 4.0
  embedder:
    _target_: geoarches.backbones.archesweather.WeatherEncodeDecodeLayer
    img_size:
    - 13
    - 121
    - 240
    emb_dim: 192
    out_emb_dim: 384
    patch_size:
    - 2
    - 2
    - 2
    surface_ch: 4
    level_ch: 6
    n_concatenated_states: 3
log: true
entity: phaz
project: atmo-diffusion
name: archesweathergen-s-ft
exp_dir: modelstore/archesweathergen-s-ft
seed: 0
max_steps: 60000
batch_size: 2
resume: true
save_step_frequency: 20000
log_freq: 100
limit_val_batches: 10
accumulate_grad_batches: 1
debug: false
mode: train
