name: Unit tests

# Trigger on push or pull request to main and dev branches.
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    name: Run unit tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12']
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      #  -----  install & configure uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      #----------------------------------------------
      #       check dependency lock file
      #----------------------------------------------
      - name: Check lock file
        run: uv lock --check
      #----------------------------------------------
      #         install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync --locked
      #----------------------------------------------
      #        download data files for tests
      #----------------------------------------------
      - name: Download stats data
        run: |
          src="https://huggingface.co/gcouairon/ArchesWeather/resolve/main"
          wget -O geoarches/stats/era5-quantiles-2016_2022.nc $src/era5-quantiles-2016_2022.nc
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run unit tests
        run: uv run pytest -v tests/ --ignore=tests/functional/
